### ISSUE TITLE
error: unable to load plugin

### ISSUE THREAD

**Issue by vhertz** [csienslab/instrim#1]
Please excuse my poor English.

I tried to compile some programs using patched afl-clang-fast.
Unfortunately, this error occurred and compiling failed.

```sh
error: unable to load plugin '/path/to/instrim/libLLVMInsTrim.so':
'/path/to/instrim/libLLVMInsTrim.so: undefined symbol:
_ZN4llvm24DisableABIBreakingChecksE'
```

OS is Ubuntu 16.04.2 on x86_64.
All prerequisite packages have already been installed (by apt-get),
and I've done all steps written in README.

What shoud I do to resolve this error?

**Comment by pzread** [comment]
Sorry I am a little busy these days. I tested it and it works on Ubuntu 17.04.
Maybe it is the version problem of clang and LLVM.
Can you check if both of your LLVM and clang are version 4.0?

**Comment by vhertz** [comment]
Thank you for your response despite your busyness.

I checked LLVM and Clang version, used to build `libLLVMInsTrim.so` and AFL’s `afl-llvm-pass.so`.
As a result, llvm-4.0 and Clang-4.0 are used.

#### libLLVMInsTrim.so
I checked `/path/to/instrim/CMakefiles/LLVMInsTrim.dir/depend.make` created by cmake.
All LLVM header files were included from `/usr/lib/llvm-4.0/include/`.

#### afl-llvm-pass.so
I edited `afl-2.52b/llvm_mode/Makefile` like this to use LLVM-4.0 and Clang-4.0 to build the lib.
```Makefile
[ … ]

LLVM_CONFIG ?= llvm-config-4.0

[ … ]

ifeq “$(origin CC)” “default”
  CC    = /usr/lib/llvm-4.0/bin/clang
  CXX   = /usr/lib/llvm-4.0/bin/clang++
endif

[ … ]
```
Aren't these enough to build them by LLVM and Clang 4.0 ?

**Comment by pzread** [comment]
In the `afl-clang-fast.c`
```
if (!strcmp(name, "afl-clang-fast++")) {
    u8* alt_cxx = getenv("AFL_CXX");
    cc_params[0] = alt_cxx ? alt_cxx : (u8*)"clang++";
} else {
    u8* alt_cc = getenv("AFL_CC");
    cc_params[0] = alt_cc ? alt_cc : (u8*)"clang";
}
```
When you run `afl-clang-fast` or `afl-clang-fast++`, it will run your default system clang. Maybe this is the problem.

In order to force it to use clang 4.0, you can try `AFL_CC=clang-4.0 afl-clang-fast ...` or `AFL_CXX=clang++-4.0 afl-clang-fast++ ...` when compiling the target program.

Sorry I still don't have time to check it on 16.04.

**Comment by vhertz** [comment]
It works by defining `AFL_CC`!
Thank you very much for your support!
