### ISSUE TITLE
Loss of coverage

### ISSUE THREAD

**Issue by vanhauser-thc** [csienslab/instrim#2]
Hi,

I tried you code and read the paper, and I think the optimization is way too aggressive and loosing coverage.

I have compiled a random code and then looked with a disassembler which basic blocks were instrumented and which were not.

instrumented basic blocks with afl-2.52b llvm_mode: 279
instrumented basic blocks with instrim: 76

Thats about only 30%of the blocks being instrumented. That already looks bad, so lets look at a specific example:

![Capture2](https://user-images.githubusercontent.com/7396244/61123081-b718ef80-a4a3-11e9-8542-f4456214ad31.PNG)

In that picture we see 7 basic blocks, the two top blocks coming from yes/no decision branches, and the bottom 3 blocks resulting in the same final basic block.

In the visible 7 basic blocks only one is instrumented. the resulting basic block from the bottom three blocks that is not visible, is also instrumented.

If we now look at the non-instrumented blocks - they are all potentially interesting and should have been instrumented.

Did you just do speed comparisons? Or did you also do coverage comparison?
(for this to be effective you have to remove all srandom() calls in afl-fuzz and replace it with a fixed srandom(123) at the start of main() to have the same PRNG results, run it for 1-24 hours and then compare the coverage of lines of code, e.g. with afl-cov)

**Comment by pzread** [comment]
InsTrim utilizes the "edge instrumentation". So for the top 2 basic blocks, the instrumented basic block in the middle can tell the different incoming edges by the value of `eax`. You can see that the `eax` is set in predecessors(top 2 basic blocks) and xored in the middle basic block when reporting.

For the bottom 3 basic blocks, the instrumented final basic block (which isn't visible) can also report which one of the bottom 3 basic blocks is taken in the same way.

Therefore, any different decision on the top branch or on the two branches in the middle (`jz short loc_401861` and `jz short loc_401883`) will result in different coverage. This is why we only instrument 2 basic blocks out of 7

**Comment by pzread** [comment]
In the paper, we did both of the speed and coverage comparisons. The details can be found in the evaluation section.

**Comment by vanhauser-thc** [comment]
That is really a subtle thing - I didnt see it.
True that is allows for a faster path documentation into the map.

I get quite a speed increase, about 20%, and that is in afl++, which is 5-10% faster than stock afl.

On the coverage side I see a very little better path discovery in afl++ when compared against the same number of executions (so disregarding that instrim is way faster), but its so minor that it quite well might be just random.

Do you know of any showstoppers that would your code make not work in newer llvm versions, say llvm 8?

**Comment by pzread** [comment]
I haven't tried to upgrade it to LLVM 8. But I think it should be straightforward (probably just change the LLVM version in CMakeFiles.txt, then LLVM 8 can directly build it)

Our goal is reducing the overhead without affecting the fuzzing behavior under the same number of execution iterations. So your result of coverage seems to match our expectation (with the same number of executions, the coverage with InsTrim should be almost same as the original one).

**Comment by pzread** [comment]
I tried to upgrade to LLVM 8. An LLVM API has a small change.
But I lack the environment to test it right now. I'd appreciate it if you can help me to test it.
You can check it on the branch https://github.com/csienslab/instrim/tree/llvm8

**Comment by vanhauser-thc** [comment]
I compiled the original with LLVM 7 without problems. I think you change is for llvm8 specifically.

I created a branch at afl++ with instrim integegrated: https://github.com/vanhauser-thc/AFLplusplus/tree/instrim - and we will move that to the main repository as its way better than afl-llvm-pass and I see no benefit in keeping afl-llvm-pass. I "just" have to integrate the whitelisting feature.

your llvm8 branch compiles but for whatever reason it crashes clang the sameway as your original code with llvm7:
```
 INSTRIM_LIB=~/instrim/branches/llvm8/libLLVMInsTrim.so MARKSET=1 ~/afl-instrim/afl-clang-fast -o /prg/AFLplusplus/branches/instrim/test-instr2 /prg/AFLplusplus/branches/instrim/test-instr.c 
afl-clang-fast 2.52b by <lszekeres@google.com>
1 locations instrumented (1,0)
Stack dump:
0.	Program arguments: /usr/lib/llvm-7/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test-instr.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -resource-dir /usr/lib/llvm-7/lib/clang/7.0.1 -D __AFL_HAVE_MANUAL_CONTROL=1 -D __AFL_COMPILER=1 -D FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 -D __AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); }) -D __AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0) -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-7/lib/clang/7.0.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdebug-compilation-dir /prg/tmp/afl-instrim.new -ferror-limit 19 -fmessage-length 80 -funroll-loops -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -load /prg/instrim/branches/llvm8/libLLVMInsTrim.so -o /tmp/test-instr-6038cf.o -x c /prg/AFLplusplus/branches/instrim/test-instr.c -faddrsig 
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 7.0.1-8 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: error: unable to execute command: Segmentation fault
clang: note: diagnostic msg: Error generating preprocessed source(s).
```
But I think this is a local problem of mine.

**Comment by vanhauser-thc** [comment]
Your LLVM 8 patch is in our branch plus < 4 support, plus support for two other extensions, notZeroCounters and whitelist support.
Plus credit for your work given in the docs plus when llvm_mode is run

With no MARKSET env the behaviour mirrors the original afl implementation, MARKSET=1 the standard instrim instrumentation and LOOPHEAD=1 the instrim Approx enhancement, correct?

Is Approx always better and should be the default? Approx seems to always be a bit faster and no drawback compared to standard instrim from how I interpret the paper.

that being said, you should a pointer to your paper in your README: https://www.ndss-symposium.org/wp-content/uploads/2018/07/bar2018_14_Hsu_paper.pdf

**Comment by pzread** [comment]
Yes, MARKSET=1 the standard instrim instrumentation and LOOPHEAD=1 the instrim Approx enhancement.

Approx doesn't instrument the loop head but only reports if the loop has been taken or not. The trade-off is AFL won't know how many times the loop iterates if there is only one basic block in the loop.

**Comment by vanhauser-thc** [comment]
perfect! made markset then the default and documented the loophead option. thanks!
